[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "py-lobs"
dynamic = ["version"]
description = 'lobs is a framework that aims to provide an easy application and library project generator.'
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
  { name = "Ricardo Marchesan", email = "rikardo.nm@proton.me" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "click ~= 8.3.0",
  "bigtree[image] ~= 1.0.2",
  "pydantic ~= 2.12.2",
  "filesizelib ~= 0.12.1",
  "annotated-types ~= 0.7.0",
  "GitPython ~= 3.1.50",
]

[project.optional-dependencies]
dev = [
  "pytest ~= 9.0.0",
]

[project.urls]
Documentation = "https://github.com/rikardonm/lobs#readme"
Issues = "https://github.com/rikardonm/lobs/issues"
Source = "https://github.com/rikardonm/lobs"

[project.scripts]
lobs = "lobs.__main__:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/lobs/version.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/lobs tests}"

[tool.hatch.build.targets.wheel]
packages = ["src/lobs"]

[tool.coverage.run]
source_pkgs = ["lobs", "tests"]
branch = true
parallel = true
omit = [
  "src/lobs/version.py",
]

[tool.coverage.paths]
lobs = ["src/lobs", "*/lobs/src/lobs"]
tests = ["tests", "*/lobs/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.black]
line-length = 120
target-version = ['py312']

[tool.flake8]
max-line-length = 120
